Set onnx version to <=1.16.1 (#754)
The installation of `onnx==1.16.2` leads to the following issue on
Windows platforms:
```
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.4.0+cu121 with CUDA 1201 (you have 2.4.0+cpu)
    Python  3.10.11 (you have 3.10.7)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Traceback (most recent call last):
  File "c:\openvinotoolkit\openvino.genai\venv\lib\site-packages\transformers\utils\import_utils.py", line 1567, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "c:\openvinotoolkit\openvino.genai\venv\lib\site-packages\optimum\onnx\graph_transformations.py", line 19, in <module>
    import onnx
  File "c:\openvinotoolkit\openvino.genai\venv\lib\site-packages\onnx\__init__.py", line 77, in <module>
    from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\openvinotoolkit\openvino.genai\llm_bench\python\benchmark.py", line 10, in <module>
    import utils.ov_utils
  File "c:\openvinotoolkit\openvino.genai\llm_bench\python\utils\ov_utils.py", line 13, in <module>
    from utils.config_class import OV_MODEL_CLASSES_MAPPING, TOKENIZE_CLASSES_MAPPING, DEFAULT_MODEL_CLASSES
  File "c:\openvinotoolkit\openvino.genai\llm_bench\python\utils\config_class.py", line 7, in <module>
    from optimum.intel.openvino import (
  File "c:\openvinotoolkit\openvino.genai\venv\lib\site-packages\optimum\intel\openvino\__init__.py", line 46, in <module>
    from .quantization import OVQuantizer
  File "c:\openvinotoolkit\openvino.genai\venv\lib\site-packages\optimum\intel\openvino\quantization.py", line 42, in <module>
    from optimum.exporters.onnx.convert import check_dummy_inputs_are_allowed
  File "c:\openvinotoolkit\openvino.genai\venv\lib\site-packages\optimum\exporters\__init__.py", line 16, in <module>
    from .tasks import TasksManager  # noqa
  File "c:\openvinotoolkit\openvino.genai\venv\lib\site-packages\optimum\exporters\tasks.py", line 173, in <module>
    class TasksManager:
  File "c:\openvinotoolkit\openvino.genai\venv\lib\site-packages\optimum\exporters\tasks.py", line 338, in TasksManager
    "clip-text-model": supported_tasks_mapping(
  File "c:\openvinotoolkit\openvino.genai\venv\lib\site-packages\optimum\exporters\tasks.py", line 117, in supported_tasks_mapping
    importlib.import_module(f"optimum.exporters.{backend}.model_configs"), config_cls_name
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\openvinotoolkit\openvino.genai\venv\lib\site-packages\optimum\exporters\onnx\model_configs.py", line 23, in <module>
    from ...onnx import merge_decoders
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "c:\openvinotoolkit\openvino.genai\venv\lib\site-packages\transformers\utils\import_utils.py", line 1557, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "c:\openvinotoolkit\openvino.genai\venv\lib\site-packages\transformers\utils\import_utils.py", line 1569, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import optimum.onnx.graph_transformations because of the following error (look up to see its traceback):
DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.
```
For more details please refer to the:
[link](https://jira.devtools.intel.com/browse/CVS-148933)

---------

Co-authored-by: Ekaterina Aidova <ekaterina.aidova@intel.com>