Add hook sample and restore usage generation config (#553)
Fix the following exception which occurs when converting the model and
running through the installation requirements_2024.2.txt
(py310_env_2024_2)
openvino-ci-69@odt-openvino-ci-69:~/wgz/openvino.genai_2024_2/openvino.genai/llm_bench/python$
python benchmark.py -m
/mnt/llm_irs/release_2024.2_5c0f38f8_stateful/llama-2-7b-chat/pytorch/dldt/FP16
[ INFO ] Traceback (most recent call last):
File
"/home/openvino-ci-69/wgz/openvino.genai_2024_2/openvino.genai/llm_bench/python/benchmark.py",
line 636, in main
iter_data_list, pretrain_time =
CASE_TO_BENCH[model_args['use_case']](model_path, framework,
args.device, model_args, args.num_iters)
File
"/home/openvino-ci-69/wgz/openvino.genai_2024_2/openvino.genai/llm_bench/python/benchmark.py",
line 298, in run_text_generation_benchmark
text_gen_fn(input_text, num, model, tokenizer, args, iter_data_list,
warmup_md5, prompt_idx, bench_hook, model_precision, proc_id)
File
"/home/openvino-ci-69/wgz/openvino.genai_2024_2/openvino.genai/llm_bench/python/benchmark.py",
line 106, in run_text_generation
    result = model.generate(
File
"/home/openvino-ci-69/wgz/py310_env_2024_2/lib/python3.10/site-packages/torch/utils/_contextlib.py",
line 115, in decorate_context
    return func(*args, **kwargs)
File
"/home/openvino-ci-69/wgz/py310_env_2024_2/lib/python3.10/site-packages/optimum/intel/openvino/modeling_decoder.py",
line 642, in generate
    result = super().generate(
File
"/home/openvino-ci-69/wgz/py310_env_2024_2/lib/python3.10/site-packages/torch/utils/_contextlib.py",
line 115, in decorate_context
    return func(*args, **kwargs)
File
"/home/openvino-ci-69/wgz/py310_env_2024_2/lib/python3.10/site-packages/transformers/generation/utils.py",
line 1576, in generate
    result = self._greedy_search(
File
"/home/openvino-ci-69/wgz/openvino.genai_2024_2/openvino.genai/llm_bench/python/utils/hook_greedy_search.py",
line 281, in new_greedy_search
raise ValueError("If `eos_token_id` is defined, make sure that
`pad_token_id` is defined.")
ValueError: If `eos_token_id` is defined, make sure that `pad_token_id`
is defined.